Repository Orange-OpenSource/Orange-Boosted-Angular, pull requests merged in 2019-06, with the labels that each got.

#72 Correction AOT build failure (private property 'pause')
  src/o-carousel/o-carousel-container.component.ts
Labels: bug

#74 fix(package.json): creating version 4.1.4-beta
  docs/app/global.ts
  package-dist.json
  package-lock.json
  package.json
Labels: bug

#76 Calendar updates
  docs/app/demos/o-calendar.component.html
  src/o-calendar/o-calendar.component.ts
Labels: bug, enhancement

#77 Swiper updates
  src/o-carousel/o-carousel-container.component.ts
Labels: enhancement

#75 Switch improve
  docs/app/demos/o-switch.component.html
  docs/app/demos/o-switch.component.ts
  docs/app/docs/o-switch.component.md
  src/o-switch/o-switch.component.ts
Labels: bug, enhancement
